# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Supersim < Formula
  desc "Supersim is a local dev environment for the Superchain"
  homepage "https://github.com/ethereum-optimism/supersim"
  version "0.1.0-alpha.22"

  on_macos do
    on_intel do
      url "https://github.com/ethereum-optimism/supersim/releases/download/0.1.0-alpha.22/supersim_Darwin_x86_64.tar.gz"
      sha256 "f8da7f2587acccd31fce2477b569e14dd2835cda7de716c900c1c36981df113b"

      def install
        bin.install "supersim"
      end
    end
    on_arm do
      url "https://github.com/ethereum-optimism/supersim/releases/download/0.1.0-alpha.22/supersim_Darwin_arm64.tar.gz"
      sha256 "31764f2fe803fd0b72668bea04ef374c4e259278da762f72cd3b89646f883a6b"

      def install
        bin.install "supersim"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ethereum-optimism/supersim/releases/download/0.1.0-alpha.22/supersim_Linux_x86_64.tar.gz"
        sha256 "b62321c8bc83c9ca9a3bd2b58ed8391d25028fe91f1b15a3bdbea16d6450d8ca"

        def install
          bin.install "supersim"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ethereum-optimism/supersim/releases/download/0.1.0-alpha.22/supersim_Linux_arm64.tar.gz"
        sha256 "1fcd6d84b5c831c09022ffc56d6df225469ef102393ba55101f114ebe9f9ff56"

        def install
          bin.install "supersim"
        end
      end
    end
  end
end
