# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Supersim < Formula
  desc "Supersim is a local dev environment for the Superchain"
  homepage "https://github.com/ethereum-optimism/supersim"
  version "0.1.0-alpha.13"

  on_macos do
    on_intel do
      url "https://github.com/ethereum-optimism/supersim/releases/download/0.1.0-alpha.13/supersim_Darwin_x86_64.tar.gz"
      sha256 "b4919a09ccfbc581202ee99ada3c6b3f696ffa01d752e6647256bd6f00d1f061"

      def install
        bin.install "supersim"
      end
    end
    on_arm do
      url "https://github.com/ethereum-optimism/supersim/releases/download/0.1.0-alpha.13/supersim_Darwin_arm64.tar.gz"
      sha256 "0b1d7a484174f5d7f6344d7258046ab895f1fd35e4a0aba65013623536272e26"

      def install
        bin.install "supersim"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ethereum-optimism/supersim/releases/download/0.1.0-alpha.13/supersim_Linux_x86_64.tar.gz"
        sha256 "d51da2b7f15e99ae53d46016b046f627a541634a1b4d34f2c078b8a741409ebc"

        def install
          bin.install "supersim"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ethereum-optimism/supersim/releases/download/0.1.0-alpha.13/supersim_Linux_arm64.tar.gz"
        sha256 "fc52e6025ddec293015c7e9f2dbee2d7b8d4a7717a825b6eabd75293156584c3"

        def install
          bin.install "supersim"
        end
      end
    end
  end
end
